### ISSUE TITLE
nex-node should propagate async workload validation failures to clients

### ISSUE THREAD

**Issue by kthomas** [synadia-io/nex#10]
This [PR](https://github.com/ConnectEverything/nex/pull/9) moved the responsibility of validating workloads to the agent. This means validation now happens asynchronously.

nex-node needs to handle workload validations asynchronously and propagate failures to clients.

**Comment by autodidaddict** [comment]
Can this be closed or is there more work to be done here?

**Comment by kthomas** [comment]
This can be closed.
