### ISSUE TITLE
Condense NodeConfiguration and NodeOptions

### ISSUE THREAD

**Issue by jordan-rash** [synadia-io/nex#102]
### Proposed change

The two structs are almost identical

### Use case

This will allow us to drop a config at preflight

**Comment by jordan-rash** [comment]
@kthomas did you're node refactor close this?

**Comment by kthomas** [comment]
> @kthomas did you're node refactor close this?

Just about. I am going to axe one of the parameters provided to `NewNode` in a small PR and then we can close this.
