### ISSUE TITLE
Nex tries to deploy workload into a VM that hasn't reported a handshake

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#134]
### Observed behavior

Start a nex node and have the agent within the first VM not report a handshake (this is pretty difficult to reproduce). A request to deploy a workload comes in and the node will attempt to deploy into that VM, and since the VM is effectively dead, the result will be a "nats: timeout"

### Expected behavior

The Nex node should abort and terminate if an agent fails to handshake. Agents failing to handshake is an indication of instability that is enough to warrant stopping the node. A missing handshake used to stop the node and no longer does, so this is a regression.

This should then never allow the situation where we attempt to deploy into a VM that hasn't given a handshake

### Nex and NATS version

Latest release of both

**Comment by kthomas** [comment]
We stopped aborting a node due to a failed handshake because if you have a number of running workloads on the node already, aborting due to a failed handshake would kill all your running workloads.

**Comment by autodidaddict** [comment]
> We stopped aborting a node due to a failed handshake because if you have a number of running workloads on the node already, aborting due to a failed handshake would kill all your running workloads.

The chances that a vm would fail a handshake after a bunch of other ones worked just fine are pretty slim. But that is an excellent point and we should have a couple levels of depth of protection here rather than just blindly shutting down.
