### ISSUE TITLE
Support a different runtime for Windows and Macos.

### ISSUE THREAD

**Issue by bjorndm** [synadia-io/nex#143]
### Proposed change

Many of us are on corporate Windows or MacOS computers, with no way to run firecracker easily. For people in this situation it would be great if nex could also run on top of another execution engine such as, e.g, podman, with podman desktop.

### Use case

Developers on corporate Windows of MacOS machines who want to test nex locally. 

### Contribution

Not software but if we havet his, then I can probably get my employer involved for buying a subscription from Synadia.

**Comment by bjorndm** [comment]
Another promising runtime environment I just discovered today is "incus" on top of LXD containers. I used LXD before and I preferred it over Docker. https://linuxcontainers.org/incus/docs/main/

**Comment by autodidaddict** [comment]
We are currently working on setting up some build tags that will allow Nex to build with the right features on different operating systems. But the general idea is that if you run a Nex node in `unsafe` mode, it will spawn the process directly and therefore not require firecracker. If it doesn't require firecracker, it can be run on a broader variety of hosts.

**Comment by jordan-rash** [comment]
At this time, we should support all major OS/Arch in `no_sandbox` mode.
