### ISSUE TITLE
OCI roadmap

### ISSUE THREAD

**Issue by NoahHahm** [synadia-io/nex#146]
### Proposed change

Limited-environment languages ​​such as Cloudflare Workers are suitable for the needs of rapid prototyping like startups, but realistically, they are difficult to adopt in companies.
If you can run an image of a personally created service on the NATS Edge
I think it will be a really good execution engine.
I would like to ask if there is a plan for priorities.
(This sentence was written using a translator, so there are some awkward parts, so please understand.)

### Use case

 run an image created at nats edge

**Comment by jordan-rash** [comment]
Hi @NoahHahm.  We are currently doing our planning for the next sprint of work which will prioritize a better DevEx and flexibility for allowing developers to iterate faster (that's the hope).  While we hesitate to make any promises, is there anything specific that you would like to see?

**Comment by NoahHahm** [comment]
I was thinking of running the image created based on the Dockerfile in nex.
I think it would be really convenient for developers if images created with a Dockerfile could be run on Edge.
this is just an opinion. I'm using Workers, but I'm eventually tapering off due to limited use by developers (javascript + npm features).
conversely, services such as Alicloud recently support Dockerfile serverless.
i think this has the advantage of allowing many developers to easily upload the server they wrote to Edge.
I will close this issue ticket.
