### ISSUE TITLE
Add update command to the CLI

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#169]
### Proposed change

Run `nex update` and it will automatically update the `nex` binary.

### Use case

For people who don't like having to remember what toolchain they used to install a given binary (was it brew? apt? nix? asdf? curl?), it just makes life so much easier if we can do `nex update` and have it update to the latest version. note that this just applies to replacing the binary being run, and doesn't affect a running process

**Comment by jordan-rash** [comment]
I had this on my todo list... thanks for making the issue

**Comment by jordan-rash** [comment]
Stage 1 complete: #174

**Comment by autodidaddict** [comment]
Should we create another issue for supporting `nex update`, or is that what this issue covers?

**Comment by jordan-rash** [comment]
Satisfied by #174 and #200
