### ISSUE TITLE
Formalize host services SDK

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#170]
### Proposed change

Host services is the set of functionality provided to Nex workloads as a built-in convenience. For example, JavaScript functions get access to a key-value bucket, an object store, basic pub/sub, and an HTTP client.

This would extract host services client code into its own "package"

### Use case

This would let code in long-running services utilize host services if they wanted to, giving people more built-in goodness when they use Nex deployments.

**Comment by jordan-rash** [comment]
@kthomas should this be closed by #195??

**Comment by autodidaddict** [comment]
This is a broader scope than the cleanup. For example, the host services client isn't a thing that can be used by external code yet

**Comment by kthomas** [comment]
> @kthomas should this be closed by #195??

#195 was needed as a prereq to formalizing an SDK, in that message headers and non-enveloped payloads were made consistent across the v8 implementation.

**Comment by autodidaddict** [comment]
Working on this now
