### ISSUE TITLE
Visualized end to end open telemetry spans

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#171]
### Proposed change

Whether it's a set of instructions or whether it's through a docker compose, we should have an "easy button" for people to be able to capture and see the open telemetry spans that we're collection

### Use case

Observability shouldn't be an afterthought

**Comment by autodidaddict** [comment]
We may want to do this before doing #132 as it might make troubleshooting that one easier.

**Comment by jordan-rash** [comment]
This worked at one point. Once I finish rootfs I'll jump on this

**Comment by jordan-rash** [comment]
Closed by #188
