### ISSUE TITLE
Implement lame duck mode

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#173]
### Proposed change

A node can be placed into lame duck mode by a remote request. This lame duck mode would:

* reject all new requests for workload start
* remove the `essential` label from all applicable running workloads
* publish a `lame_duck_entered` event
* all subsequent heartbeats would include the `lame_duck` flag

Once in lame duck mode, a node cannot be "un-lame-duck'ed". The only acceptable state after lame duck is termination.

### Use case

We may want to prepare a node for maintenance, update, pending network partition, or maybe just a particularly long graceful shutdown. Implementing a request to enter lame duck mode would accomplish this.

**Comment by jordan-rash** [comment]
🦆

**Comment by autodidaddict** [comment]
Closed by #177
