### ISSUE TITLE
Support namespace pings

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#193]
### Proposed change

Support the ability to "probe" a nexus (cluster of nex nodes) for a given namespace. So instead of pinging and getting a reply from all machines, instead get a reply from each workload in a given namespace.

The ping and ping filtering system could use a bit of a refactor anyway, especially to accommodate another filter like this.

### Use case

Probe for "everything running in this namespace".

**Comment by autodidaddict** [comment]
I think the best approach here might to change the response type of the `WPING` operation to be a set of matching workloads, and then allow the workload Id to be left off of the ping topic, which would essentially result in a namespace-wide workload ping.

**Comment by kthomas** [comment]
It might still be useful to allow for pinging the running agents in a namespace, in addition to this proposed `WPING`, or ping for running workloads.

**Comment by autodidaddict** [comment]
the `WPING` already exists to ping a specific workload ID or name. This issue only recommends supporting not specifying a workload filter on that wping.

This is a discovery feature, pinging the running agents is a health check feature
