### ISSUE TITLE
Attempt to Validate Binaries 

### ISSUE THREAD

**Issue by jordan-rash** [synadia-io/nex#233]
### Proposed change

We are not currently validating binaries are being deployed to machines that support the binaries architecture.  For example, if we attempt to deploy a linux/arm64 binary to a no-sandbox windows node, it will attempt to run it.

This issue proposes we attempt to validate a binary as best we can prior to deployment using the file headers.

### Use case

`nex run` and `nex devrun` should error if a binary is attempted to run on a machine with a different OS/Arch

**Comment by autodidaddict** [comment]
to be more specific, `nex run` and `nex devrun` should error because the nex node rejects the run request prior to attempting to run/deploy the executable
