### ISSUE TITLE
Default Workload Types Innaccurate 

### ISSUE THREAD

**Issue by jordan-rash** [synadia-io/nex#234]
### Observed behavior

Currently, every build it being created with default workloads of [this](https://github.com/synadia-io/nex/blob/3d248329e3b430a367e5dc30fd7fa4a904cf562a/internal/models/config.go#L145).  Not all OS/Arch support all workloads and this value should be build tag dependent

### Expected behavior

Different defaults based on OS/Arch

### Nex and NATS version

Current

**Comment by kthomas** [comment]
Should this be closed?

**Comment by jordan-rash** [comment]
Closed by #240
