### ISSUE TITLE
dynamic config method when creating a Firecreaker VM

### ISSUE THREAD

**Issue by NoahHahm** [synadia-io/nex#241]
### Proposed change

When creating a new Firecracker VM with machine_template config, the cpu and memory sizes are fixed. (e.g. if I create 100 new VMs, they will all have the same vcpu cores and memory size).
Is it be possible to flexibly adjust the size of each Firecracker VM at the time of VM creation, e.g. depending on the specific tag?
If possible, I would like to know how to dynamically adjust its size and start it.

### Use case

Workload "A" needs 2vCPU, and workload "B" might need 4vCPU.

we do not simply execute simple function workloads, but rather use processes that must be maintained for a long time, such as batch/build/scheduling.

**Comment by jordan-rash** [comment]
Thanks Noah!  I _think_ there is existing work on this somewhere and it might not have landed yet.  Let me investigate and Ill let you know.  Either way, we agree on this being a required feature from production use cases

**Comment by jordan-rash** [comment]
Closing in favor of #60.  Feel free to follow up on progress there...and thanks for the feedback!
