### ISSUE TITLE
Workloads that fail to start still appear in workload count

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#295]
### Observed behavior

When getting a list of nodes (via ping), the returned list of node information is still counting workloads that never properly started or failed to start up properly.

### Expected behavior

Workloads that die or that never fail to start should not be counted in the running workload list

### Nex and NATS version

Nex main

### Host environment

mac and linux

### Steps to reproduce

Deploy a workload that panics

**Comment by kthomas** [comment]
This was fixed in #324
