### ISSUE TITLE
Circular workload undeploy

### ISSUE THREAD

**Issue by kthomas** [synadia-io/nex#296]
### Observed behavior

The nex node attempts to stop an undeployed workload upon receipt of the `workload_undeployed` event when it was stopped by the user via API. This results in a false negative logs indicating the workload in question failed to stop.

### Expected behavior

When the user stops a workload, the node should not attempt to stop that workload upon receipt of the emitted agent `workload_undeployed` event.

### Nex and NATS version

All versions.

**Comment by autodidaddict** [comment]
Since all these events have the source node on them, we could probably choose to disregard inbound events that came from the same node. 🤔

**Comment by kthomas** [comment]
This was fixed in #328.
