### ISSUE TITLE
Firecracker at $3K-10K per runtime hour is unusable

### ISSUE THREAD

**Issue by MikeHawkesCapventis** [synadia-io/nex#330]
### Proposed change

I was trying to get this working and decided to look at a .metal instance on AWS. We're taling EEK! Before I've even got a base configuration running, I'm already into thousands of dollars of spend. Firecracker is really, really, really expensive to get running on a hosted environment. It's just not feasible to use. It's a real shame because I was very excited by the prospect of running this, but I can't justify the cost.

### Use case

A sensible price!

### Contribution

I'd contribute if I could get it running without spending a fortune.

**Comment by jordan-rash** [comment]
Thanks for the feedback.  Yea, the major clouds are expensive, but you can experiment with any Linux box and if you really want to use in a cloud at lower cost, you can try _nosandbox_ mode. We can run `nex` on free tiers when not using firecracker

**Comment by MikeHawkesCapventis** [comment]
It was more of an observation than anything else - I wanted to get the functions working for JS (akin to Lambda) and realised I'd need Firecracker to get that going. I work on a Mac, so spent a fruitless day trying to get an environment to work, Parallels, Qemu and so on - realising this wasn't going to happen, I looked at the prices before instantiating one of the metal machines and fainted. Thousands of dollars an hour just make this layer is completely out of most people's price range. So, if NATS is relying on Firecracker too heavily, and this is its future direction, then it's going to be a real shame that the smaller enterprises won't be able to afford to deploy such an exciting feature. I want to be able to deploy this kind of capability as it reduces the whole infrastructure management workload - but I don't know many CTO's that will want to spend even $1K per hour let alone the $26K per hour top end. That's major tech territory! 

Yes we can run without the sandbox for development, but I can't deploy to production, nor can I develop things like JS functions or WASM segments, because they need Firecracker. Unless I' m missing something, that is ... happy to be corrected.

**Comment by ripienaar** [comment]
@MikeHawkesCapventis above comments are saying you can run it on any KVM based VM not just metal. There are very cheap options to do this. Is there a reason you won't want any of those, like maybe you only support AWS?

**Comment by MikeHawkesCapventis** [comment]
Yep. Even on M3, it doesn't want to work! Having said that, I've been deploying without Firecracker and it's pretty damned impressive!

**Comment by hpvd** [comment]
just a comment:
not being able to rely on aws (gcp looks a little better but there are also many restriction on which machines it is working) looks like a real **strategic draw back** to me.
Especially if you are thinking about a rollout world wide or for latency or regulation-requirement reasons near to the customers.
In this case you would have to deal with many local providers which eats some of the simplicity Nex is promising.
The other solution using bare metal from the big 3 kills the cost advantages brought by nats and nex.

@jordan-rash  hmmm what do you think of reopen this for these reasons?

**Comment by hpvd** [comment]
at OVP you can read in their Cloud FAQs:

**Is nested virtualization supported?**

Yes and no.

Yes because it's enabled (we provide vmx flag to your instance), which means you can start any virtualization technology that relies on this in your instance (such as KVM, QEMU, VirtualBox, Xen, HyperV, etc.).

No because as soon we will live-migrate your instance (and this can happen any time, based on our hypervisor management), then your kernel may panic.

**Comment by hpvd** [comment]
> @MikeHawkesCapventis above comments are saying you can run it on any KVM based VM not just metal. There are very cheap options to do this. Is there a reason you won't want any of those, like maybe you only support AWS?

=> yes, because of the auto-migration see previous comment

**Comment by hpvd** [comment]
Do anyone have different practical experience? And a fair priced virtual KVM provider is fine for long running-services?

And/or any idea advice how one can approach a typical cloud use case where one need to run services in different locations/countries without having to deal with many different local vendors?

**Comment by hpvd** [comment]
opened a general issue about firecracker usage in nex: https://github.com/synadia-io/nex/issues/450
