### ISSUE TITLE
Add support for OS- and CPU- specific artifacts when downloading from NATS

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#395]
### Proposed change

Add a bit of intelligence to artifact downloading:
* If the workload type is function (JavaScript or wasm), no changes
* If the workload type is `native`:
  * Attempt to download `{path}_{os}_{arch}` (e.g. `echoservice_darwin_amd64`) where `os` and `arch` are the operating system and CPU architecture of the _Nex node_ attempting to download the artifact
  * If no such artifact exists, try and download just `{path}`

### Use case

In the current version of Nex, it will pull whatever artifact is indicated by the URL in the start workload request. This means that if you accidentally give Nex the URL for a `darwin` artifact and send it to a Nex node running on Linux, the workload will fail to start.

This would allow for Nex nodes running on different CPUs and operating systems to all be given the same start workload command and it will "just work" and download the appropriate binary

**Comment by hpvd** [comment]
this is not directly but somehow related, since both are about matching needs and capabilities:
https://github.com/synadia-io/nex/issues/451

**Comment by jordan-rash** [comment]
This is actually complete in V3 branch...documentation to come
