### ISSUE TITLE
node up should always start the first vm on the first available IP in the CIDR

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#40]
Right now node up just continues allocating IP addresses. In production it won't take long for the IPs to run out.

Note that this behavior will happen regardless of how many times the node is started. Basically after 254 VMs from a fresh start, we're going to run out. So I see the requirements as follows:

* Start the node fresh with an empty /var/lib/cni so the first VM gets the `.2` address
* Before putting the 253rd VM into the pool, we should reset /var/lib/cni so that the next VM gets `.2`

**Comment by kthomas** [comment]
Closed by https://github.com/synadia-io/nex/pull/115
