### ISSUE TITLE
Ensure that Nex can be built on non-Linux operating systems

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#68]
### Proposed change

Allows for Nex to be built/released for non-Linux operating systems

### Use case

The primary use case for this is for people who want to remotely control/operate Nex nodes from machines that don't meet the node execution requirements but can still act as control clients. This could be either Windows or MacOS.

Ideally if you run `nex node ...` on non-Linux, you'd get an error message rather than the current behavior, which I believe fails to compile on MacOS.

**Comment by jordan-rash** [comment]
I think this was closed by #78
