### ISSUE TITLE
Expose open telemetry metrics

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#72]
### Proposed change

Follow the same pattern(s) as the NATS server (where/if appropriate) to allow Nex nodes to emit (or be scraped for) metrics. The ability to _export_ should be considered the primary goal (OTLP) while supporting _scraping_ should only be done if we get that for free or "for cheap" when we're setting up the metrics and exporting. We shouldn't use any specific vendor libraries like Jaeger or Prometheus, everything should be otel/OTLP standards.

Some gauges that I think we'll want ("deployed" includes all workload types, incl. functions):

- [x] deployed workload count
- [x] deployed workload count in namespace
- [x] deployed bytes count (size of total deployed workloads)
- [x] deployed bytes count in namespace
- [x] allocated memory total (based on firecracker machine config)
- [x] allocated memory in namespace
- [x] allocated vcpu count (based on fc vm config)
- [x] allocated vcpu count in namespace

Counters:

- [x] function trigger count total
- [x] function trigger count for workload
- [x] function trigger count for namespace
- [ ] function failure count total
- [ ] function failure count for workload
- [ ] function failure count for namespace
- [x] function execution elapsed time
- [x] function execution elapsed time for namespace
- [x] total function execution time across all funcs

### Use case

Operators managing a fleet of Nex nodes will need this feature

**Comment by jordan-rash** [comment]
+1
