### ISSUE TITLE
Nex CLI should be aware of nats context

### ISSUE THREAD

**Issue by autodidaddict** [synadia-io/nex#86]
### Proposed change

When the Nex CLI is performing a task that requires a connection to the NATS server, we should be able to detect if a nats context is available and selected and even potentially offer the ability to override the nats context.

### Use case

If someone isn't using the default NATS URL for their development server, then they have to add (at least) `--server` to all of their nex commands. We should make it much easier and detect/reuse the nats context.

**Comment by codegangsta** [comment]
Just a note for anyone who wants to contribute this, there is a `natscontext` package that is super easy to integrate while also passing in any options for overrides, exactly like how the nats cli works:

https://pkg.go.dev/github.com/nats-io/jsm.go/natscontext

**Comment by autodidaddict** [comment]
There's a pr for this inbound

**Comment by gedw99** [comment]
huge thanks you !!!

you just made this much easier: https://github.com/ServiceWeaver/weaver/issues/725
